# Generated by Django 3.0.1 on 2020-01-05 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TodoList',
            new_name='TodoTask',
        ),
    ]
